<div class="modal fade" id="modalAgregarGeneral" tabindex="-1">
    <form action="{{ route('cirugiageneral.store') }}" method="POST"> @csrf <div class="modal-dialog modal-lg"><div class="modal-content"><div class="modal-header"><h5 class="modal-title">Agregar Cirugía General</h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="row"><div class="col-md-4 mb-3"><label class="form-label">ID Cirugía</label><input type="text" name="id_cirugia_general" class="form-control" required></div><div class="col-md-4 mb-3"><label class="form-label">Fecha Ingreso</label><input type="date" name="fecha_ingreso" class="form-control"></div><div class="col-md-4 mb-3"><label class="form-label">Fecha Egreso</label><input type="date" name="fecha_egreso" class="form-control"></div><div class="col-md-8 mb-3"><label class="form-label">Pieza Patológica</label><input type="text" name="pieza_patologica" class="form-control"></div><div class="col-md-4 mb-3"><label class="form-label">Tipo</label><select name="tipoCirugia" class="form-select"><option value="programada">Programada</option><option value="urgencia">Urgencia</option></select></div><div class="col-12 mb-3"><label class="form-label">Región Anatómica</label><input type="text" name="region_anatomica" class="form-control" required></div><div class="col-md-4 mb-3"><label class="form-label">Paciente</label><select name="id_paciente" class="form-select" required><option value="">Seleccione...</option>@foreach($pacientes as $paciente)<option value="{{ $paciente->id_paciente }}">{{ $paciente->nombre_completo }}</option>@endforeach</select></div><div class="col-md-4 mb-3"><label class="form-label">Doctor</label><select name="id_doctor" class="form-select" required><option value="">Seleccione...</option>@foreach($doctores as $doctor)<option value="{{ $doctor->id_doctor }}">{{ $doctor->nombre_completo }}</option>@endforeach</select></div><div class="col-md-4 mb-3"><label class="form-label">Diagnóstico</label><select name="id_diagnostico" class="form-select" required><option value="">Seleccione...</option>@foreach($diagnosticos as $diagnostico)<option value="{{ $diagnostico->id_diagnostico }}">{{ $diagnostico->nombre_diagnostico }}</option>@endforeach</select></div></div></div><div class="modal-footer"><button type="submit" class="btn btn-primary">Guardar</button></div></div></div></form>
</div>

<div class="modal fade" id="modalEditarGeneral" tabindex="-1">
    <form id="formEditarGeneral" method="POST"> @csrf @method('PUT') <div class="modal-dialog modal-lg"><div class="modal-content"><div class="modal-header"><h5 class="modal-title">Editar Cirugía General</h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="row">
        <div class="col-md-4 mb-3"><label class="form-label">ID Cirugía</label><input type="text" id="edit_id_cirugia_general" class="form-control" readonly></div>
        <div class="col-md-4 mb-3"><label class="form-label">Fecha Ingreso</label><input type="date" name="fecha_ingreso" id="edit_fecha_ingreso_general" class="form-control"></div>
        <div class="col-md-4 mb-3"><label class="form-label">Fecha Egreso</label><input type="date" name="fecha_egreso" id="edit_fecha_egreso_general" class="form-control"></div>
        <div class="col-md-8 mb-3"><label class="form-label">Pieza Patológica</label><input type="text" name="pieza_patologica" id="edit_pieza_patologica" class="form-control"></div>
        <div class="col-md-4 mb-3"><label class="form-label">Tipo</label><select name="tipoCirugia" id="edit_tipoCirugia_general" class="form-select"><option value="programada">Programada</option><option value="urgencia">Urgencia</option></select></div>
        <div class="col-12 mb-3"><label class="form-label">Región Anatómica</label><input type="text" name="region_anatomica" id="edit_region_anatomica" class="form-control" required></div>
        <div class="col-md-4 mb-3"><label class="form-label">Paciente</label><select name="id_paciente" id="edit_id_paciente_general" class="form-select" required><option value="">Seleccione...</option>@foreach($pacientes as $paciente)<option value="{{ $paciente->id_paciente }}">{{ $paciente->nombre_completo }}</option>@endforeach</select></div>
        <div class="col-md-4 mb-3"><label class="form-label">Doctor</label><select name="id_doctor" id="edit_id_doctor_general" class="form-select" required><option value="">Seleccione...</option>@foreach($doctores as $doctor)<option value="{{ $doctor->id_doctor }}">{{ $doctor->nombre_completo }}</option>@endforeach</select></div>
        <div class="col-md-4 mb-3"><label class="form-label">Diagnóstico</label><select name="id_diagnostico" id="edit_id_diagnostico_general" class="form-select" required><option value="">Seleccione...</option>@foreach($diagnosticos as $diagnostico)<option value="{{ $diagnostico->id_diagnostico }}">{{ $diagnostico->nombre_diagnostico }}</option>@endforeach</select></div>
    </div></div><div class="modal-footer"><button type="submit" class="btn btn-warning">Guardar Cambios</button></div></div></div></form>
</div>

<div class="modal fade" id="modalEliminarGeneral" tabindex="-1">
    <form id="formEliminarGeneral" method="POST"> @csrf @method('DELETE') <div class="modal-dialog"><div class="modal-content"><div class="modal-header"><h5 class="modal-title">Eliminar Cirugía</h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><p>¿Estás seguro de que deseas eliminar este registro?</p></div><div class="modal-footer"><button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button><button type="submit" class="btn btn-danger">Eliminar</button></div></div></div></form>
</div>